name: Merge To Master SFDX Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy-to-diego:
    name: "Deploy to Diego Org"
    runs-on: ubuntu-latest
    steps:
      - name: "Describe Job"
        run: echo "Github Action running on ${{ runner.os }}"

      - name: "Install SF CLI"
        run: npm install @salesforce/cli --global

      - name: "Install SFDX Git Delta"
        run: 
          echo y | sf plugins install sfdx-git-delta

      - name: "Checkout source code with all history"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: "Populate auth file with SALESFORCE_JWT_SECRET_KEY secret"
        run: echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key

      - name: "Authorise into Salesforce PROD"
        run: sfdx org login jwt --client-id ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwt-key-file server.key --username=${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --set-default-dev-hub

      - name: "Prepare Deployment Package from Delta"
        run: sf sgd source delta --from "${{ github.event.before }}" --to "${{ github.event.after }}" --output . --source force-app/main/default

      - name: "Upload package.xml to artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: "Deployment Package"
          path: package/package.xml

      - name: "Deploy"
        shell: bash
        run: |
          echo "-- Starting Deployment --"
          if grep -q '<types>' package/package.xml;
          then
            echo "-- found deployment package. Starting deployment --"
            cat ./package/package.xml
            sfdx project deploy start --target-org ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --manifest package/package.xml --test-level RunLocalTests --wait 180 --verbose
          else
            echo "-- No deployment package found --"
          fi
