name: Merge To Master SFDX Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy-to-diego:
    name: "Deploy to Diego Org"
    runs-on: ubuntu-latest
    steps:
      - name: "Describe Job"
        run: echo "Github Action running on ${{ runner.os }}"

      - name: "Install SFDX CLI"
        run: npm install sfdx-cli -g

      - name: "Install SFDX Git Delta"
        run: npm install sfdx-git-delta@latest -g

      - name: "Checkout source code history"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: "Populate auth file with "
        run: | 
          touch server.key
          echo  ${{ secrets.SALESFORCE_JWT_SECRET_KEY }} > ./server.key

      - name: "Authorise into Salesforce PROD"
        run: sfdx force:auth:jwt:grant --clientid=${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile=server.key --username=${{ secrets.SALESFORCE_DEVHUB_USERNAME }} --setdefaultdevhubusername

      - name: "Prepare Deployment Package from Delta"
        run: sfdx sgd:source:delta --from "${{ github.event.before }}" --to "${{ github.event.after }}" --output . --source force-app/main/default

      - name: "Upload package.xml to artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: "Deployment Package"
          path: autoPackage/package.xml

      - name: "Deploy"
        shell: bash
        run: |
          echo "-- Starting Deployment --"
          if grep -q '<types>' autoPackage/package.xml;
          then
            echo "-- found deployment package. Starting deployment --"
            cat ./autoPackage/package.xml
            sfdx force:source:deploy --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME }} -x autoPackage/package.xml --testlevel RunLocalTests --wait -1 --verbose
          else
            echo "-- No deployment package found --"
          fi
